# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: CI caching

on:
  push:
    branches: [ main ]
    paths-ignore:
      - "README.md"
      - "**.txt"
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
        - os: ubuntu-latest
          path: ~/.cache/pip
        - os: macos-latest
          path: ~/Library/Caches/pip
        - os: windows-latest
          path: ~\AppData\Local\pip\Cache
    steps:
    - uses: actions/cache@v2
      with:
        path: ${{ matrix.path }}
        key: |
          ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          ${{ runner.os }}-pip-${{ hashFiles('**/requirements_python27.txt') }}
        restore-keys: |
         ${{ runner.os }}-pip-
